version: '3'

services:
    # gogus:
    #     build:
    #         context: .
    #         dockerfile: go.dockerfile
    #     ports:
    #         - 8082:9990
    #     volumes:
    #         - ./:/go
    #     networks:
    #       gus-go-network:
    #         ipv4_address: 172.16.0.2
    
    # gogus:
    #     build:
    #         context: .
    #         dockerfile: cplus.dockerfile
    #     container_name: cplus
    #     ports:
    #         - 80:80
    #     volumes:
    #         - ./:/var/www/html
    #     networks:
    #       gus-go-network:
    #         ipv4_address: 172.16.0.2

    gusunix:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        container_name: gusunix
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        networks:
          gus-go-network:
            ipv4_address: 172.16.0.2

networks:
    gus-go-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.16.0.0/16"
